zookeeper:
  image: eventuateio/eventuate-zookeeper:0.1.0.RELEASE
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888

rabbitmq:
  image: eventuateio/eventuate-rabbitmq:0.1.0.RELEASE
  ports:
    - 5672:5672
